---
name: deploying static site
run-name: deploying static website by user ${{github.actor}}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  static-wbsite-deploy-on-apache-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: cloning repo
        uses: actions/checkout@v4
      - name: rsync deployments
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /var/www/html/
          remote_host: 54.162.250.78
          remote_user: ubuntu
          remote_key: ${{ secrets.DEPLOY_KEY }}
…
